//Shared html elements
const dataTitle = document.getElementById("dataTitle");
const dataDisplay = document.getElementById("dataDisplay");
const viewSelect = document.getElementById("viewSelect");

//Contains 20 samples. See categories in more detail at https://www.kaggle.com/datasets/jawadkhattak/us-flight-delay-from-january-2017-july-2022
const jsonSample = [
  {
    "year": 2019,
    "month": 10,
    "carrier": "9E",
    "carrier_name": "Endeavor Air Inc.",
    "airport": "CHS",
    "airport_name": "Charleston, SC: Charleston AFB/International",
    "arr_flights": 47,
    "arr_del15": 2,
    "carrier_ct": 0,
    "weather_ct": 0,
    "nas_ct": 1,
    "security_ct": 0,
    "late_aircraft_ct": 1,
    "arr_cancelled": 1,
    "arr_diverted": 0,
    "arr_delay": 128,
    "carrier_delay": 0,
    "weather_delay": 0,
    "nas_delay": 70,
    "security_delay": 0,
    "late_aircraft_delay": 58
    
  },
  {
    "year": 2018,
    "month": 11,
    "carrier": "B6",
    "carrier_name": "JetBlue Airways",
    "airport": "DEN",
    "airport_name": "Denver, CO: Denver International",
    "arr_flights": 89,
    "arr_del15": 24,
    "carrier_ct": 12.97,
    "weather_ct": 0,
    "nas_ct": 5.39,
    "security_ct": 0,
    "late_aircraft_ct": 5.64,
    "arr_cancelled": 0,
    "arr_diverted": 0,
    "arr_delay": 1487,
    "carrier_delay": 927,
    "weather_delay": 0,
    "nas_delay": 262,
    "security_delay": 0,
    "late_aircraft_delay": 298
    
  },
  {
    "year": 2022,
    "month": 1,
    "carrier": "YV",
    "carrier_name": "Mesa Airlines Inc.",
    "airport": "FAR",
    "airport_name": "Fargo, ND: Hector International",
    "arr_flights": 90,
    "arr_del15": 20,
    "carrier_ct": 9.89,
    "weather_ct": 0,
    "nas_ct": 5.96,
    "security_ct": 0,
    "late_aircraft_ct": 4.15,
    "arr_cancelled": 12,
    "arr_diverted": 0,
    "arr_delay": 1364,
    "carrier_delay": 629,
    "weather_delay": 0,
    "nas_delay": 250,
    "security_delay": 0,
    "late_aircraft_delay": 485
    
  },
  {
    "year": 2022,
    "month": 6,
    "carrier": "YX",
    "carrier_name": "Republic Airline",
    "airport": "IAD",
    "airport_name": "Washington, DC: Washington Dulles International",
    "arr_flights": 346,
    "arr_del15": 43,
    "carrier_ct": 19.35,
    "weather_ct": 1,
    "nas_ct": 8.54,
    "security_ct": 0,
    "late_aircraft_ct": 14.11,
    "arr_cancelled": 23,
    "arr_diverted": 0,
    "arr_delay": 2828,
    "carrier_delay": 890,
    "weather_delay": 58,
    "nas_delay": 497,
    "security_delay": 0,
    "late_aircraft_delay": 1383
    
  },
  {
    "year": 2019,
    "month": 12,
    "carrier": "YV",
    "carrier_name": "Mesa Airlines Inc.",
    "airport": "TLH",
    "airport_name": "Tallahassee, FL: Tallahassee International",
    "arr_flights": 48,
    "arr_del15": 15,
    "carrier_ct": 5,
    "weather_ct": 0,
    "nas_ct": 4.19,
    "security_ct": 0,
    "late_aircraft_ct": 5.81,
    "arr_cancelled": 1,
    "arr_diverted": 1,
    "arr_delay": 1120,
    "carrier_delay": 445,
    "weather_delay": 0,
    "nas_delay": 145,
    "security_delay": 0,
    "late_aircraft_delay": 530
    
  },
  {
    "year": 2017,
    "month": 8,
    "carrier": "EV",
    "carrier_name": "ExpressJet Airlines Inc.",
    "airport": "CLE",
    "airport_name": "Cleveland, OH: Cleveland-Hopkins International",
    "arr_flights": 737,
    "arr_del15": 149,
    "carrier_ct": 43.63,
    "weather_ct": 2.58,
    "nas_ct": 34.2,
    "security_ct": 0,
    "late_aircraft_ct": 68.59,
    "arr_cancelled": 35,
    "arr_diverted": 1,
    "arr_delay": 15363,
    "carrier_delay": 4804,
    "weather_delay": 187,
    "nas_delay": 4697,
    "security_delay": 0,
    "late_aircraft_delay": 5675
    
  },
  {
    "year": 2021,
    "month": 1,
    "carrier": "UA",
    "carrier_name": "United Air Lines Inc.",
    "airport": "LIH",
    "airport_name": "Lihue, HI: Lihue Airport",
    "arr_flights": 16,
    "arr_del15": 1,
    "carrier_ct": 1,
    "weather_ct": 0,
    "nas_ct": 0,
    "security_ct": 0,
    "late_aircraft_ct": 0,
    "arr_cancelled": 0,
    "arr_diverted": 0,
    "arr_delay": 34,
    "carrier_delay": 34,
    "weather_delay": 0,
    "nas_delay": 0,
    "security_delay": 0,
    "late_aircraft_delay": 0
    
  },
  {
    "year": 2020,
    "month": 2,
    "carrier": "B6",
    "carrier_name": "JetBlue Airways",
    "airport": "CLE",
    "airport_name": "Cleveland, OH: Cleveland-Hopkins International",
    "arr_flights": 100,
    "arr_del15": 14,
    "carrier_ct": 6.41,
    "weather_ct": 0,
    "nas_ct": 3.64,
    "security_ct": 0,
    "late_aircraft_ct": 3.95,
    "arr_cancelled": 0,
    "arr_diverted": 0,
    "arr_delay": 942,
    "carrier_delay": 478,
    "weather_delay": 0,
    "nas_delay": 167,
    "security_delay": 0,
    "late_aircraft_delay": 297
    
  },
  {
    "year": 2022,
    "month": 1,
    "carrier": "AA",
    "carrier_name": "American Airlines Inc.",
    "airport": "DTW",
    "airport_name": "Detroit, MI: Detroit Metro Wayne County",
    "arr_flights": 302,
    "arr_del15": 51,
    "carrier_ct": 27.47,
    "weather_ct": 1.05,
    "nas_ct": 7.02,
    "security_ct": 0.65,
    "late_aircraft_ct": 14.81,
    "arr_cancelled": 11,
    "arr_diverted": 0,
    "arr_delay": 2896,
    "carrier_delay": 1400,
    "weather_delay": 104,
    "nas_delay": 304,
    "security_delay": 28,
    "late_aircraft_delay": 1060
    
  },
  {
    "year": 2019,
    "month": 7,
    "carrier": "OO",
    "carrier_name": "SkyWest Airlines Inc.",
    "airport": "TUL",
    "airport_name": "Tulsa, OK: Tulsa International",
    "arr_flights": 259,
    "arr_del15": 54,
    "carrier_ct": 12.9,
    "weather_ct": 4.78,
    "nas_ct": 24.03,
    "security_ct": 0,
    "late_aircraft_ct": 12.3,
    "arr_cancelled": 0,
    "arr_diverted": 1,
    "arr_delay": 2505,
    "carrier_delay": 662,
    "weather_delay": 379,
    "nas_delay": 750,
    "security_delay": 0,
    "late_aircraft_delay": 714
    
  },
  {
    "year": 2020,
    "month": 6,
    "carrier": "WN",
    "carrier_name": "Southwest Airlines Co.",
    "airport": "SAT",
    "airport_name": "San Antonio, TX: San Antonio International",
    "arr_flights": 608,
    "arr_del15": 42,
    "carrier_ct": 14.56,
    "weather_ct": 4.17,
    "nas_ct": 4.84,
    "security_ct": 0.83,
    "late_aircraft_ct": 17.61,
    "arr_cancelled": 9,
    "arr_diverted": 1,
    "arr_delay": 1972,
    "carrier_delay": 490,
    "weather_delay": 350,
    "nas_delay": 145,
    "security_delay": 44,
    "late_aircraft_delay": 943
    
  },
  {
    "year": 2020,
    "month": 4,
    "carrier": "OO",
    "carrier_name": "SkyWest Airlines Inc.",
    "airport": "LAN",
    "airport_name": "Lansing, MI: Capital Region International",
    "arr_flights": 70,
    "arr_del15": 7,
    "carrier_ct": 4.43,
    "weather_ct": 0,
    "nas_ct": 2.57,
    "security_ct": 0,
    "late_aircraft_ct": 0,
    "arr_cancelled": 33,
    "arr_diverted": 0,
    "arr_delay": 410,
    "carrier_delay": 327,
    "weather_delay": 0,
    "nas_delay": 83,
    "security_delay": 0,
    "late_aircraft_delay": 0
    
  },
  {
    "year": 2021,
    "month": 3,
    "carrier": "OO",
    "carrier_name": "SkyWest Airlines Inc.",
    "airport": "EAR",
    "airport_name": "Kearney, NE: Kearney Regional",
    "arr_flights": 62,
    "arr_del15": 2,
    "carrier_ct": 1,
    "weather_ct": 0,
    "nas_ct": 0,
    "security_ct": 0,
    "late_aircraft_ct": 1,
    "arr_cancelled": 3,
    "arr_diverted": 1,
    "arr_delay": 36,
    "carrier_delay": 15,
    "weather_delay": 0,
    "nas_delay": 0,
    "security_delay": 0,
    "late_aircraft_delay": 21
    
  },
  {
    "year": 2018,
    "month": 6,
    "carrier": "EV",
    "carrier_name": "ExpressJet Airlines Inc.",
    "airport": "FWA",
    "airport_name": "Fort Wayne, IN: Fort Wayne International",
    "arr_flights": 29,
    "arr_del15": 9,
    "carrier_ct": 3.2,
    "weather_ct": 0,
    "nas_ct": 0.84,
    "security_ct": 0,
    "late_aircraft_ct": 4.97,
    "arr_cancelled": 1,
    "arr_diverted": 0,
    "arr_delay": 940,
    "carrier_delay": 399,
    "weather_delay": 0,
    "nas_delay": 131,
    "security_delay": 0,
    "late_aircraft_delay": 410
    
  },
  {
    "year": 2019,
    "month": 8,
    "carrier": "YV",
    "carrier_name": "Mesa Airlines Inc.",
    "airport": "GJT",
    "airport_name": "Grand Junction, CO: Grand Junction Regional",
    "arr_flights": 1,
    "arr_del15": 0,
    "carrier_ct": 0,
    "weather_ct": 0,
    "nas_ct": 0,
    "security_ct": 0,
    "late_aircraft_ct": 0,
    "arr_cancelled": 0,
    "arr_diverted": 0,
    "arr_delay": 0,
    "carrier_delay": 0,
    "weather_delay": 0,
    "nas_delay": 0,
    "security_delay": 0,
    "late_aircraft_delay": 0
    
  },
  {
    "year": 2021,
    "month": 10,
    "carrier": "DL",
    "carrier_name": "Delta Air Lines Inc.",
    "airport": "SJC",
    "airport_name": "San Jose, CA: Norman Y. Mineta San Jose International",
    "arr_flights": 213,
    "arr_del15": 24,
    "carrier_ct": 13.11,
    "weather_ct": 0,
    "nas_ct": 7.5,
    "security_ct": 0,
    "late_aircraft_ct": 3.39,
    "arr_cancelled": 0,
    "arr_diverted": 0,
    "arr_delay": 1719,
    "carrier_delay": 1399,
    "weather_delay": 0,
    "nas_delay": 192,
    "security_delay": 0,
    "late_aircraft_delay": 128
    
  },
  {
    "year": 2022,
    "month": 4,
    "carrier": "NK",
    "carrier_name": "Spirit Air Lines",
    "airport": "SNA",
    "airport_name": "Santa Ana, CA: John Wayne Airport-Orange County",
    "arr_flights": 150,
    "arr_del15": 45,
    "carrier_ct": 8.16,
    "weather_ct": 0,
    "nas_ct": 29.66,
    "security_ct": 0,
    "late_aircraft_ct": 7.18,
    "arr_cancelled": 9,
    "arr_diverted": 0,
    "arr_delay": 2698,
    "carrier_delay": 660,
    "weather_delay": 0,
    "nas_delay": 1490,
    "security_delay": 0,
    "late_aircraft_delay": 548
    
  },
  {
    "year": 2021,
    "month": 1,
    "carrier": "YX",
    "carrier_name": "Republic Airline",
    "airport": "RDU",
    "airport_name": "Raleigh/Durham, NC: Raleigh-Durham International",
    "arr_flights": 448,
    "arr_del15": 36,
    "carrier_ct": 17.61,
    "weather_ct": 0.3,
    "nas_ct": 15.95,
    "security_ct": 0,
    "late_aircraft_ct": 2.14,
    "arr_cancelled": 2,
    "arr_diverted": 1,
    "arr_delay": 2297,
    "carrier_delay": 1495,
    "weather_delay": 22,
    "nas_delay": 701,
    "security_delay": 0,
    "late_aircraft_delay": 79
    
  },
  {
    "year": 2020,
    "month": 12,
    "carrier": "YX",
    "carrier_name": "Republic Airline",
    "airport": "CAE",
    "airport_name": "Columbia, SC: Columbia Metropolitan",
    "arr_flights": 96,
    "arr_del15": 6,
    "carrier_ct": 5.63,
    "weather_ct": 0,
    "nas_ct": 0.37,
    "security_ct": 0,
    "late_aircraft_ct": 0,
    "arr_cancelled": 0,
    "arr_diverted": 0,
    "arr_delay": 278,
    "carrier_delay": 269,
    "weather_delay": 0,
    "nas_delay": 9,
    "security_delay": 0,
    "late_aircraft_delay": 0
    
  }
];

//Place your code in your sections
//Larry

//Jasper

//Pamela